model_name: "resnet50"
num_epochs: 100
is_load: True
path_to_load: "./model/05-06-2023-10-33/checkpoints/Epoch_28_loss_1.87021.pt"
path_to_info_for_model: "./model/05-06-2023-10-33/"
path_to_data: "./data/train/train"
path_to_annotations: "./data/train/annotations.csv"
batch_size: 768
output_dir: models
img_size: [64, 224]